services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_api
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
